/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrincessEventsRouteImport } from './routes/princess-events'
import { Route as HeroEventsRouteImport } from './routes/hero-events'
import { Route as IndexRouteImport } from './routes/index'

const PrincessEventsRoute = PrincessEventsRouteImport.update({
  id: '/princess-events',
  path: '/princess-events',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroEventsRoute = HeroEventsRouteImport.update({
  id: '/hero-events',
  path: '/hero-events',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hero-events': typeof HeroEventsRoute
  '/princess-events': typeof PrincessEventsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hero-events': typeof HeroEventsRoute
  '/princess-events': typeof PrincessEventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hero-events': typeof HeroEventsRoute
  '/princess-events': typeof PrincessEventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hero-events' | '/princess-events'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hero-events' | '/princess-events'
  id: '__root__' | '/' | '/hero-events' | '/princess-events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HeroEventsRoute: typeof HeroEventsRoute
  PrincessEventsRoute: typeof PrincessEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/princess-events': {
      id: '/princess-events'
      path: '/princess-events'
      fullPath: '/princess-events'
      preLoaderRoute: typeof PrincessEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hero-events': {
      id: '/hero-events'
      path: '/hero-events'
      fullPath: '/hero-events'
      preLoaderRoute: typeof HeroEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HeroEventsRoute: HeroEventsRoute,
  PrincessEventsRoute: PrincessEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
